### PR TITLE
Fix network selection if more than one network labeled 'flowforge'

### LINKED ISSUE #65: flowforge instance can sometimes get created with the wrong network
### Current Behavior

For users that may be running many docker containers, they may want to consolidate their flowforge docker containers with the rest of their running containers.  
So a user can possibly end up with multiple networks with the word "flowforge" in it to customize their docker environment.  
If this is the case, flowforge will sometimes end up creating new docker instances on the wrong network, because it is designed to look for the first network with the word "flowforge" in it.  

### Expected Behavior

Creating a new flowforge instance should just default to the same network the `forge`  container is running on, rather than searching for a network with the word `flowforge` in it.  

### Steps To Reproduce

Create more than one network with the word `flowforge` in it.  
ie... `flowforge_flowforge` and another network called `flowforge_default`.  

### Environment

- FlowForge version: 1.8.0
- Node.js version: 16.20.0
- npm version:
- Platform/OS: flowforge docker-compose running in debian linux (ubuntu22)
- Browser: chrome

### PR DESCRIPTION
**Pull request by hardillb**
fixes #65 
## Description

Looks up the network the forge app is using to ensure the correct network is assigned to NR Instances.

Tested with local builds

## Related Issue(s)
#65

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Includes a DB migration? -> add the `area:migration` label

### CODE REVIEW

File: docker.js [hunk 1]
```diff
@@ -180,6 +179,32 @@ module.exports = {
...
+                this._app.log.info(`[docker] using network ${filteredNetworks[0].Name}`)
+                this._network = filteredNetworks[0].Name
+            } else {
+                this._app.log.info('[docker] unable to find network')
+                process.exit(-9)
+            }
+        } else {
+            this._app.log.info(`[docker] using network ${networks[0].Name}`)
+            this._network = networks[0].Name
+        }
```
Comment (Steve-Mcl) [inline docker.js:206]:
```suggestion
        } else of (networks.length === 1) {
            this._app.log.info(`[docker] using network ${networks[0].Name}`)
            this._network = networks[0].Name
        } else {
            this._app.log.info('[docker] unable to find network')
            process.exit(-9)
        }
```

Ben i see there is a check + exit if non of the filtered networks match but there is no check for 0 networks. 

Is it worth adding a definitive test for `network.length` === 1 otherwise exit in the same manor?

Comment (hardillb) [reply docker.js:206]: It shouldn't be possible if started with the docker-compose.yml, but might as well cover all options

Comment (Steve-Mcl) [reply docker.js]: I though that might be the case and wanted to check with you.

**Review by Steve-Mcl — APPROVED** [review]
